runtime: nodejs
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
beta_settings:
  cloud_sql_instances: kitab-288808:europe-west6:kitab=tcp:3306
